version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/autoflo
      - PYTHON_SERVICE_URL=http://python-service:5000
    depends_on:
      - db
      - python-service

  # Python service for Autogen integration
  python-service:
    build:
      context: ./integration/autogen
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./integration/autogen:/app
    environment:
      - PYTHONUNBUFFERED=1
      - AUTOGEN_API_KEY=${AUTOGEN_API_KEY}

  # Database service
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=autoflo
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
